export { default as Logo_img } from "./logo.png";
export { default as Academia_img } from "./academia.jpg";
export { default as Basquete_img } from "./basketball.jpg";
export { default as Corrida_img } from "./corrida.jpg";
export { default as Futebol_img } from "./futebol.jpg";
export { default as Piscinas_img } from "./piscinas.jpg";
export { default as Tenis_img } from "./tenis.jpg";
export { default as Login_img } from "./login_icon.gif";
export { default as Loading_img } from "./loading.gif";